Use new function formatting and add/update commands/functions

diff --git a/tag-bedrock/bin/demyx-install b/tag-bedrock/bin/demyx-install
--- a/tag-bedrock/bin/demyx-install
+++ b/tag-bedrock/bin/demyx-install
@@ -2,32 +2,63 @@
 # Demyx
 # https://demyx.sh
 set -euo pipefail
+#
+#   Main.
+#
+demyx_install() {
+    # Support for old variables
+    [[ -n "${WORDPRESS_DB_HOST:-}" ]] && DEMYX_DB_HOST="$WORDPRESS_DB_HOST"
+    [[ -n "${WORDPRESS_DB_NAME:-}" ]] && DEMYX_DB_NAME="$WORDPRESS_DB_NAME"
+    [[ -n "${WORDPRESS_DB_PASSWORD:-}" ]] && DEMYX_DB_PASSWORD="$WORDPRESS_DB_PASSWORD"
+    [[ -n "${WORDPRESS_DB_USER:-}" ]] && DEMYX_DB_USER="$WORDPRESS_DB_USER"
+    [[ -n "${WORDPRESS_DOMAIN:-}" ]] && DEMYX_DOMAIN="$WORDPRESS_DOMAIN"
+    [[ -n "${WORDPRESS_SSL:-}" ]] && DEMYX_SSL="$WORDPRESS_SSL"
 
-# Support for old variables
-[[ -n "${WORDPRESS_DB_HOST:-}" ]] && DEMYX_DB_HOST="$WORDPRESS_DB_HOST"
-[[ -n "${WORDPRESS_DB_NAME:-}" ]] && DEMYX_DB_NAME="$WORDPRESS_DB_NAME"
-[[ -n "${WORDPRESS_DB_PASSWORD:-}" ]] && DEMYX_DB_PASSWORD="$WORDPRESS_DB_PASSWORD"
-[[ -n "${WORDPRESS_DB_USER:-}" ]] && DEMYX_DB_USER="$WORDPRESS_DB_USER"
-[[ -n "${WORDPRESS_DOMAIN:-}" ]] && DEMYX_DOMAIN="$WORDPRESS_DOMAIN"
-[[ -n "${WORDPRESS_SSL:-}" ]] && DEMYX_SSL="$WORDPRESS_SSL"
-# Define variables
-DEMYX_ENV="$DEMYX"/.env
-DEMYX_PROTO="http://$DEMYX_DOMAIN"
-[[ "$DEMYX_SSL" = true ]] && DEMYX_PROTO="https://$DEMYX_DOMAIN"
+    # Define variables
+    DEMYX_ENV="$DEMYX"/.env
+    DEMYX_PROTO="http://$DEMYX_DOMAIN"
+    [[ "$DEMYX_SSL" = true ]] && DEMYX_PROTO="https://$DEMYX_DOMAIN"
 
-if [[ ! -d "$DEMYX"/web ]]; then
-    echo "[demyx] Bedrock is missing, copying files now ..."
-    tar -xzf "$DEMYX_CONFIG"/bedrock.tgz -C "$DEMYX"
-fi
+    demyx_install_config
+}
+#
+#   Config.
+#
+demyx_install_config() {
+    if [[ ! -d "$DEMYX"/web ]]; then
+        echo "[demyx] Bedrock is missing, copying files now ..."
+        tar -xzf "$DEMYX_CONFIG"/bedrock.tgz -C "$DEMYX"
+    fi
 
-if [[ -n "$(grep example.com "$DEMYX_ENV" || true)" ]]; then
-    echo "[demyx] Configuring Bedrock .env file ..."
-    sed -i "s|WP_HOME=.*|WP_HOME=$DEMYX_PROTO|g" "$DEMYX_ENV"
-    sed -i "s|database_name|$DEMYX_DB_NAME|g" "$DEMYX_ENV"
-    sed -i "s|database_user|$DEMYX_DB_USER|g" "$DEMYX_ENV"
-    sed -i "s|database_password|$DEMYX_DB_PASSWORD|g" "$DEMYX_ENV"
-    sed -i "s|# DB_HOST='localhost'|DB_HOST='$DEMYX_DB_HOST'|g" "$DEMYX_ENV"
-    sed -i "s|WP_ENV=.*|WP_ENV=production|g" "$DEMYX_ENV"
-    SALT="$(wget -qO- https://api.wordpress.org/secret-key/1.1/salt/ | sed "s|define('||g" | sed "s|',|=|g" | sed "s| ||g" | sed "s|);||g")"
-    printf '%s\n' "g/generateme/d" a "$SALT" . w | ed -s "$DEMYX_ENV"
-fi
+    if [[ -n "$(grep example.com "$DEMYX_ENV" || true)" ]]; then
+        echo "[demyx] Configuring Bedrock .env file ..."
+        sed -i "s|WP_HOME=.*|WP_HOME=$DEMYX_PROTO|g" "$DEMYX_ENV"
+        sed -i "s|database_name|$DEMYX_DB_NAME|g" "$DEMYX_ENV"
+        sed -i "s|database_user|$DEMYX_DB_USER|g" "$DEMYX_ENV"
+        sed -i "s|database_password|$DEMYX_DB_PASSWORD|g" "$DEMYX_ENV"
+        sed -i "s|# DB_HOST='localhost'|DB_HOST='$DEMYX_DB_HOST'|g" "$DEMYX_ENV"
+        sed -i "s|WP_ENV=.*|WP_ENV=production|g" "$DEMYX_ENV"
+        SALT="$(wget -qO- https://api.wordpress.org/secret-key/1.1/salt/ | sed "s|define('||g" | sed "s|',|=|g" | sed "s| ||g" | sed "s|);||g")"
+        printf '%s\n' "g/generateme/d" a "$SALT" . w | ed -s "$DEMYX_ENV"
+
+        # Configure wp-config.php
+        # shellcheck disable=SC2153
+        wp core install \
+            --admin_email="$DEMYX_WP_EMAIL" \
+            --admin_password="$DEMYX_WP_PASSWORD" \
+            --admin_user="$DEMYX_WP_USERNAME" \
+            --skip-email \
+            --title="$DEMYX_DOMAIN" \
+            --url="${DEMYX_PROTO}://${DEMYX_DOMAIN}"
+
+        # Update permalinks
+        wp rewrite structure '/%category%/%postname%/'
+
+        # Update timezone
+        wp option update timezone_string "$TZ"
+    fi
+}
+#
+#   Init.
+#
+demyx_install
